"""Implement hierarchical idea-box module

Revision ID: 0d74d702847b
Revises: 7931a4c5c1eb
Create Date: 2025-10-16 18:38:12.933137

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d74d702847b'
down_revision: Union[str, Sequence[str], None] = '7931a4c5c1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkmetadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkmetadata_url'), 'linkmetadata', ['url'], unique=True)
    op.create_table('ideafolder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideafolder_name'), 'ideafolder', ['name'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('idea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'LINK', 'IMAGE', name='ideatype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('link_metadata_id', sa.Uuid(), nullable=True),
    sa.Column('generated_task_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['ideafolder.id'], ),
    sa.ForeignKeyConstraint(['generated_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['link_metadata_id'], ['linkmetadata.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_is_pinned'), 'idea', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_idea_title'), 'idea', ['title'], unique=False)
    op.create_table('ideataglink',
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('idea_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ideataglink')
    op.drop_index(op.f('ix_idea_title'), table_name='idea')
    op.drop_index(op.f('ix_idea_is_pinned'), table_name='idea')
    op.drop_table('idea')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_ideafolder_name'), table_name='ideafolder')
    op.drop_table('ideafolder')
    op.drop_index(op.f('ix_linkmetadata_url'), table_name='linkmetadata')
    op.drop_table('linkmetadata')
    # ### end Alembic commands ###
