"""Add calendar events table

Revision ID: 7931a4c5c1eb
Revises: 7dadb64b4dfc
Create Date: 2025-10-16 11:22:27.621711

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7931a4c5c1eb'
down_revision: Union[str, Sequence[str], None] = '7dadb64b4dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarevent_end_time'), 'calendarevent', ['end_time'], unique=False)
    op.create_index(op.f('ix_calendarevent_start_time'), 'calendarevent', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendarevent_title'), 'calendarevent', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendarevent_title'), table_name='calendarevent')
    op.drop_index(op.f('ix_calendarevent_start_time'), table_name='calendarevent')
    op.drop_index(op.f('ix_calendarevent_end_time'), table_name='calendarevent')
    op.drop_table('calendarevent')
    # ### end Alembic commands ###
