"""add IdeaBox tables and some fixes

Revision ID: 7b876cc0dd36
Revises: 0d74d702847b
Create Date: 2025-10-18 19:34:18.880909

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b876cc0dd36'
down_revision: Union[str, Sequence[str], None] = '0d74d702847b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('idea_type', sa.Enum('TEXT', 'LINK', 'IMAGE', name='ideatype'), nullable=False))
    op.drop_column('idea', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('type', sa.VARCHAR(length=5), nullable=False))
    op.drop_column('idea', 'idea_type')
    # ### end Alembic commands ###
